### ISSUE TITLE
貌似文档中的404错误代码执行有错误

### ISSUE THREAD

**Issue by zhangmazi** [zither/slim-chinese-documentation#2]
slim v3.0 develop
如何监听404错误并自定义错误？

**Comment by zhangmazi** [comment]
OK，我已经解决了。

**Comment by zither** [comment]
那部分文档相关的代码已经修改过了，但是文档还没有更新，在最新的代码中 `Slim\App` 自身已经不是 container 了，相应的错误 Handler 需要定义到 `$app->container`  容器中。
